// Mocks generated by Mockito 5.4.6 from annotations
// in induscore/test/providers/current_user_kuerzel_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart'
    as _i3;
import 'package:firebase_core/firebase_core.dart' as _i2;
import 'package:induscore/models/app_user.dart' as _i11;
import 'package:induscore/models/grade.dart' as _i7;
import 'package:induscore/models/klasse.dart' as _i8;
import 'package:induscore/models/leistungsnachweis.dart' as _i9;
import 'package:induscore/models/ln_exemption.dart' as _i15;
import 'package:induscore/models/schueler_unterricht.dart' as _i16;
import 'package:induscore/models/student.dart' as _i5;
import 'package:induscore/models/subject.dart' as _i6;
import 'package:induscore/services/auth_service.dart' as _i14;
import 'package:induscore/services/firestore_service.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseApp_0 extends _i1.SmartFake implements _i2.FirebaseApp {
  _FakeFirebaseApp_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActionCodeInfo_1 extends _i1.SmartFake
    implements _i3.ActionCodeInfo {
  _FakeActionCodeInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_2 extends _i1.SmartFake
    implements _i4.UserCredential {
  _FakeUserCredential_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_3 extends _i1.SmartFake
    implements _i4.ConfirmationResult {
  _FakeConfirmationResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePasswordValidationStatus_4 extends _i1.SmartFake
    implements _i3.PasswordValidationStatus {
  _FakePasswordValidationStatus_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserMetadata_5 extends _i1.SmartFake implements _i3.UserMetadata {
  _FakeUserMetadata_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiFactor_6 extends _i1.SmartFake implements _i4.MultiFactor {
  _FakeMultiFactor_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdTokenResult_7 extends _i1.SmartFake implements _i3.IdTokenResult {
  _FakeIdTokenResult_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_8 extends _i1.SmartFake implements _i4.User {
  _FakeUser_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStudent_9 extends _i1.SmartFake implements _i5.Student {
  _FakeStudent_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubject_10 extends _i1.SmartFake implements _i6.Subject {
  _FakeSubject_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGrade_11 extends _i1.SmartFake implements _i7.Grade {
  _FakeGrade_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKlasse_12 extends _i1.SmartFake implements _i8.Klasse {
  _FakeKlasse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLeistungsnachweis_13 extends _i1.SmartFake
    implements _i9.Leistungsnachweis {
  _FakeLeistungsnachweis_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMergeResult_14 extends _i1.SmartFake implements _i10.MergeResult {
  _FakeMergeResult_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppUser_15 extends _i1.SmartFake implements _i11.AppUser {
  _FakeAppUser_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuth extends _i1.Mock implements _i4.FirebaseAuth {
  MockFirebaseAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_0(this, Invocation.getter(#app)),
          )
          as _i2.FirebaseApp);

  @override
  set app(_i2.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  set tenantId(String? tenantId) => super.noSuchMethod(
    Invocation.setter(#tenantId, tenantId),
    returnValueForMissingStub: null,
  );

  @override
  set customAuthDomain(String? customAuthDomain) => super.noSuchMethod(
    Invocation.setter(#customAuthDomain, customAuthDomain),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i12.Future<void> useAuthEmulator(
    String? host,
    int? port, {
    bool? automaticHostMapping = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #useAuthEmulator,
              [host, port],
              {#automaticHostMapping: automaticHostMapping},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> applyActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#applyActionCode, [code]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i3.ActionCodeInfo> checkActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#checkActionCode, [code]),
            returnValue: _i12.Future<_i3.ActionCodeInfo>.value(
              _FakeActionCodeInfo_1(
                this,
                Invocation.method(#checkActionCode, [code]),
              ),
            ),
          )
          as _i12.Future<_i3.ActionCodeInfo>);

  @override
  _i12.Future<void> confirmPasswordReset({
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPasswordReset, [], {
              #code: code,
              #newPassword: newPassword,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i4.UserCredential> createUserWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#createUserWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<_i4.UserCredential> getRedirectResult() =>
      (super.noSuchMethod(
            Invocation.method(#getRedirectResult, []),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#getRedirectResult, []),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  bool isSignInWithEmailLink(String? emailLink) =>
      (super.noSuchMethod(
            Invocation.method(#isSignInWithEmailLink, [emailLink]),
            returnValue: false,
          )
          as bool);

  @override
  _i12.Stream<_i4.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i12.Stream<_i4.User?>.empty(),
          )
          as _i12.Stream<_i4.User?>);

  @override
  _i12.Stream<_i4.User?> idTokenChanges() =>
      (super.noSuchMethod(
            Invocation.method(#idTokenChanges, []),
            returnValue: _i12.Stream<_i4.User?>.empty(),
          )
          as _i12.Stream<_i4.User?>);

  @override
  _i12.Stream<_i4.User?> userChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userChanges, []),
            returnValue: _i12.Stream<_i4.User?>.empty(),
          )
          as _i12.Stream<_i4.User?>);

  @override
  _i12.Future<void> sendPasswordResetEmail({
    required String? email,
    _i3.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> sendSignInLinkToEmail({
    required String? email,
    required _i3.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendSignInLinkToEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setLanguageCode(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguageCode, [languageCode]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setSettings({
    bool? appVerificationDisabledForTesting = false,
    String? userAccessGroup,
    String? phoneNumber,
    String? smsCode,
    bool? forceRecaptchaFlow,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSettings, [], {
              #appVerificationDisabledForTesting:
                  appVerificationDisabledForTesting,
              #userAccessGroup: userAccessGroup,
              #phoneNumber: phoneNumber,
              #smsCode: smsCode,
              #forceRecaptchaFlow: forceRecaptchaFlow,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> setPersistence(_i3.Persistence? persistence) =>
      (super.noSuchMethod(
            Invocation.method(#setPersistence, [persistence]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i4.UserCredential> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInAnonymously, []),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<_i4.UserCredential> signInWithCredential(
    _i3.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCredential, [credential]),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithCredential, [credential]),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<_i4.UserCredential> signInWithCustomToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCustomToken, [token]),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithCustomToken, [token]),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<_i4.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<_i4.UserCredential> signInWithEmailLink({
    required String? email,
    required String? emailLink,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailLink, [], {
              #email: email,
              #emailLink: emailLink,
            }),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithEmailLink, [], {
                  #email: email,
                  #emailLink: emailLink,
                }),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<_i4.UserCredential> signInWithProvider(
    _i3.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithProvider, [provider]),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithProvider, [provider]),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<_i4.ConfirmationResult> signInWithPhoneNumber(
    String? phoneNumber, [
    _i4.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i12.Future<_i4.ConfirmationResult>.value(
              _FakeConfirmationResult_3(
                this,
                Invocation.method(#signInWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i12.Future<_i4.ConfirmationResult>);

  @override
  _i12.Future<_i4.UserCredential> signInWithPopup(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPopup, [provider]),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithPopup, [provider]),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<void> signInWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithRedirect, [provider]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<String> verifyPasswordResetCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPasswordResetCode, [code]),
            returnValue: _i12.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#verifyPasswordResetCode, [code]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<void> verifyPhoneNumber({
    String? phoneNumber,
    _i3.PhoneMultiFactorInfo? multiFactorInfo,
    required _i3.PhoneVerificationCompleted? verificationCompleted,
    required _i3.PhoneVerificationFailed? verificationFailed,
    required _i3.PhoneCodeSent? codeSent,
    required _i3.PhoneCodeAutoRetrievalTimeout? codeAutoRetrievalTimeout,
    String? autoRetrievedSmsCodeForTesting,
    Duration? timeout = const Duration(seconds: 30),
    int? forceResendingToken,
    _i3.MultiFactorSession? multiFactorSession,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneNumber, [], {
              #phoneNumber: phoneNumber,
              #multiFactorInfo: multiFactorInfo,
              #verificationCompleted: verificationCompleted,
              #verificationFailed: verificationFailed,
              #codeSent: codeSent,
              #codeAutoRetrievalTimeout: codeAutoRetrievalTimeout,
              #autoRetrievedSmsCodeForTesting: autoRetrievedSmsCodeForTesting,
              #timeout: timeout,
              #forceResendingToken: forceResendingToken,
              #multiFactorSession: multiFactorSession,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> revokeTokenWithAuthorizationCode(
    String? authorizationCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#revokeTokenWithAuthorizationCode, [
              authorizationCode,
            ]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> initializeRecaptchaConfig() =>
      (super.noSuchMethod(
            Invocation.method(#initializeRecaptchaConfig, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i3.PasswordValidationStatus> validatePassword(
    _i4.FirebaseAuth? auth,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validatePassword, [auth, password]),
            returnValue: _i12.Future<_i3.PasswordValidationStatus>.value(
              _FakePasswordValidationStatus_4(
                this,
                Invocation.method(#validatePassword, [auth, password]),
              ),
            ),
          )
          as _i12.Future<_i3.PasswordValidationStatus>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i4.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified =>
      (super.noSuchMethod(Invocation.getter(#emailVerified), returnValue: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  _i3.UserMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeUserMetadata_5(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i3.UserMetadata);

  @override
  List<_i3.UserInfo> get providerData =>
      (super.noSuchMethod(
            Invocation.getter(#providerData),
            returnValue: <_i3.UserInfo>[],
          )
          as List<_i3.UserInfo>);

  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i13.dummyValue<String>(this, Invocation.getter(#uid)),
          )
          as String);

  @override
  _i4.MultiFactor get multiFactor =>
      (super.noSuchMethod(
            Invocation.getter(#multiFactor),
            returnValue: _FakeMultiFactor_6(
              this,
              Invocation.getter(#multiFactor),
            ),
          )
          as _i4.MultiFactor);

  @override
  _i12.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, [forceRefresh]),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<_i3.IdTokenResult> getIdTokenResult([
    bool? forceRefresh = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdTokenResult, [forceRefresh]),
            returnValue: _i12.Future<_i3.IdTokenResult>.value(
              _FakeIdTokenResult_7(
                this,
                Invocation.method(#getIdTokenResult, [forceRefresh]),
              ),
            ),
          )
          as _i12.Future<_i3.IdTokenResult>);

  @override
  _i12.Future<_i4.UserCredential> linkWithCredential(
    _i3.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithCredential, [credential]),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#linkWithCredential, [credential]),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<_i4.UserCredential> linkWithProvider(
    _i3.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithProvider, [provider]),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#linkWithProvider, [provider]),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<_i4.UserCredential> reauthenticateWithProvider(
    _i3.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithProvider, [provider]),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<_i4.UserCredential> reauthenticateWithPopup(
    _i3.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithPopup, [provider]),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#reauthenticateWithPopup, [provider]),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<void> reauthenticateWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithRedirect, [provider]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i4.UserCredential> linkWithPopup(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPopup, [provider]),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#linkWithPopup, [provider]),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<void> linkWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithRedirect, [provider]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i4.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i4.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i12.Future<_i4.ConfirmationResult>.value(
              _FakeConfirmationResult_3(
                this,
                Invocation.method(#linkWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i12.Future<_i4.ConfirmationResult>);

  @override
  _i12.Future<_i4.UserCredential> reauthenticateWithCredential(
    _i3.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithCredential, [credential]),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> sendEmailVerification([
    _i3.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, [actionCodeSettings]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i4.User> unlink(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#unlink, [providerId]),
            returnValue: _i12.Future<_i4.User>.value(
              _FakeUser_8(this, Invocation.method(#unlink, [providerId])),
            ),
          )
          as _i12.Future<_i4.User>);

  @override
  _i12.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updatePhoneNumber(
    _i3.PhoneAuthCredential? phoneCredential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneNumber, [phoneCredential]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updatePhotoURL(String? photoURL) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoURL, [photoURL]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i3.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#verifyBeforeUpdateEmail, [
              newEmail,
              actionCodeSettings,
            ]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i14.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Stream<_i4.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i12.Stream<_i4.User?>.empty(),
          )
          as _i12.Stream<_i4.User?>);

  @override
  _i12.Future<_i4.UserCredential> signInWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#signInWithEmailPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<_i4.UserCredential> registerWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmailPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#registerWithEmailPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<_i4.UserCredential> createUserWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [
              email,
              password,
            ]),
            returnValue: _i12.Future<_i4.UserCredential>.value(
              _FakeUserCredential_2(
                this,
                Invocation.method(#createUserWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i12.Future<_i4.UserCredential>);

  @override
  _i12.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> changePassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [currentPassword, newPassword]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i10.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Stream<List<_i5.Student>> getStudents() =>
      (super.noSuchMethod(
            Invocation.method(#getStudents, []),
            returnValue: _i12.Stream<List<_i5.Student>>.empty(),
          )
          as _i12.Stream<List<_i5.Student>>);

  @override
  _i12.Future<_i5.Student> getStudent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getStudent, [id]),
            returnValue: _i12.Future<_i5.Student>.value(
              _FakeStudent_9(this, Invocation.method(#getStudent, [id])),
            ),
          )
          as _i12.Future<_i5.Student>);

  @override
  _i12.Future<String> createStudent(_i5.Student? student) =>
      (super.noSuchMethod(
            Invocation.method(#createStudent, [student]),
            returnValue: _i12.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#createStudent, [student]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<void> updateStudent(_i5.Student? student) =>
      (super.noSuchMethod(
            Invocation.method(#updateStudent, [student]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteStudent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStudent, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Stream<List<_i5.Student>> getStudentsByKlasse(String? klasseId) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentsByKlasse, [klasseId]),
            returnValue: _i12.Stream<List<_i5.Student>>.empty(),
          )
          as _i12.Stream<List<_i5.Student>>);

  @override
  _i12.Stream<List<_i6.Subject>> getSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getSubjects, []),
            returnValue: _i12.Stream<List<_i6.Subject>>.empty(),
          )
          as _i12.Stream<List<_i6.Subject>>);

  @override
  _i12.Future<_i6.Subject> getSubject(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSubject, [id]),
            returnValue: _i12.Future<_i6.Subject>.value(
              _FakeSubject_10(this, Invocation.method(#getSubject, [id])),
            ),
          )
          as _i12.Future<_i6.Subject>);

  @override
  _i12.Future<String> createSubject(_i6.Subject? subject) =>
      (super.noSuchMethod(
            Invocation.method(#createSubject, [subject]),
            returnValue: _i12.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#createSubject, [subject]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<void> updateSubject(_i6.Subject? subject) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubject, [subject]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteSubject(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubject, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Stream<List<_i7.Grade>> getGrades() =>
      (super.noSuchMethod(
            Invocation.method(#getGrades, []),
            returnValue: _i12.Stream<List<_i7.Grade>>.empty(),
          )
          as _i12.Stream<List<_i7.Grade>>);

  @override
  _i12.Stream<List<_i7.Grade>> getGradesByLeistungsnachweis(
    String? leistungsnachweisId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGradesByLeistungsnachweis, [
              leistungsnachweisId,
            ]),
            returnValue: _i12.Stream<List<_i7.Grade>>.empty(),
          )
          as _i12.Stream<List<_i7.Grade>>);

  @override
  _i12.Stream<List<_i7.Grade>> getGradesByStudent(String? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#getGradesByStudent, [studentId]),
            returnValue: _i12.Stream<List<_i7.Grade>>.empty(),
          )
          as _i12.Stream<List<_i7.Grade>>);

  @override
  _i12.Future<_i7.Grade> getGrade(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGrade, [id]),
            returnValue: _i12.Future<_i7.Grade>.value(
              _FakeGrade_11(this, Invocation.method(#getGrade, [id])),
            ),
          )
          as _i12.Future<_i7.Grade>);

  @override
  _i12.Future<String> createGrade(_i7.Grade? grade) =>
      (super.noSuchMethod(
            Invocation.method(#createGrade, [grade]),
            returnValue: _i12.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#createGrade, [grade]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<void> saveGrades(List<_i7.Grade>? grades) =>
      (super.noSuchMethod(
            Invocation.method(#saveGrades, [grades]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateGrade(_i7.Grade? grade) =>
      (super.noSuchMethod(
            Invocation.method(#updateGrade, [grade]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteGrade(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGrade, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteGradesByLeistungsnachweis(
    String? leistungsnachweisId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGradesByLeistungsnachweis, [
              leistungsnachweisId,
            ]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Stream<List<_i8.Klasse>> getKlassen() =>
      (super.noSuchMethod(
            Invocation.method(#getKlassen, []),
            returnValue: _i12.Stream<List<_i8.Klasse>>.empty(),
          )
          as _i12.Stream<List<_i8.Klasse>>);

  @override
  _i12.Future<_i8.Klasse> getKlasse(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getKlasse, [id]),
            returnValue: _i12.Future<_i8.Klasse>.value(
              _FakeKlasse_12(this, Invocation.method(#getKlasse, [id])),
            ),
          )
          as _i12.Future<_i8.Klasse>);

  @override
  _i12.Stream<List<_i8.Klasse>> getKlassenBySchuljahrAndBeruf(
    String? schuljahr,
    String? berufCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getKlassenBySchuljahrAndBeruf, [
              schuljahr,
              berufCode,
            ]),
            returnValue: _i12.Stream<List<_i8.Klasse>>.empty(),
          )
          as _i12.Stream<List<_i8.Klasse>>);

  @override
  _i12.Future<String> createKlasse(_i8.Klasse? klasse) =>
      (super.noSuchMethod(
            Invocation.method(#createKlasse, [klasse]),
            returnValue: _i12.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#createKlasse, [klasse]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<void> updateKlasse(_i8.Klasse? klasse) =>
      (super.noSuchMethod(
            Invocation.method(#updateKlasse, [klasse]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteKlasse(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteKlasse, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Stream<List<_i9.Leistungsnachweis>> getLeistungsnachweise() =>
      (super.noSuchMethod(
            Invocation.method(#getLeistungsnachweise, []),
            returnValue: _i12.Stream<List<_i9.Leistungsnachweis>>.empty(),
          )
          as _i12.Stream<List<_i9.Leistungsnachweis>>);

  @override
  _i12.Future<_i9.Leistungsnachweis> getLeistungsnachweis(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getLeistungsnachweis, [id]),
            returnValue: _i12.Future<_i9.Leistungsnachweis>.value(
              _FakeLeistungsnachweis_13(
                this,
                Invocation.method(#getLeistungsnachweis, [id]),
              ),
            ),
          )
          as _i12.Future<_i9.Leistungsnachweis>);

  @override
  _i12.Stream<List<_i9.Leistungsnachweis>> getLeistungsnachweiseByKlasse(
    String? klasseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLeistungsnachweiseByKlasse, [klasseId]),
            returnValue: _i12.Stream<List<_i9.Leistungsnachweis>>.empty(),
          )
          as _i12.Stream<List<_i9.Leistungsnachweis>>);

  @override
  _i12.Stream<List<_i9.Leistungsnachweis>> getLeistungsnachweiseBySubject(
    String? subjectId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLeistungsnachweiseBySubject, [subjectId]),
            returnValue: _i12.Stream<List<_i9.Leistungsnachweis>>.empty(),
          )
          as _i12.Stream<List<_i9.Leistungsnachweis>>);

  @override
  _i12.Future<String> createLeistungsnachweis(_i9.Leistungsnachweis? ln) =>
      (super.noSuchMethod(
            Invocation.method(#createLeistungsnachweis, [ln]),
            returnValue: _i12.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#createLeistungsnachweis, [ln]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<void> updateLeistungsnachweis(_i9.Leistungsnachweis? ln) =>
      (super.noSuchMethod(
            Invocation.method(#updateLeistungsnachweis, [ln]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteLeistungsnachweis(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLeistungsnachweis, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i8.Klasse?> findExistingKlasse({
    required String? berufCode,
    required int? jahrgangsstufe,
    required int? zeitgruppeNummer,
    required int? laufendeNummer,
    required String? schuljahr,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findExistingKlasse, [], {
              #berufCode: berufCode,
              #jahrgangsstufe: jahrgangsstufe,
              #zeitgruppeNummer: zeitgruppeNummer,
              #laufendeNummer: laufendeNummer,
              #schuljahr: schuljahr,
            }),
            returnValue: _i12.Future<_i8.Klasse?>.value(),
          )
          as _i12.Future<_i8.Klasse?>);

  @override
  _i12.Future<List<_i5.Student>> getStudentsByKlasseOnce(String? klasseId) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentsByKlasseOnce, [klasseId]),
            returnValue: _i12.Future<List<_i5.Student>>.value(<_i5.Student>[]),
          )
          as _i12.Future<List<_i5.Student>>);

  @override
  _i12.Future<String> importKlasseMitSchuelern({
    required _i8.Klasse? klasse,
    required List<_i5.Student>? schueler,
    String? importSource = 'pdf',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#importKlasseMitSchuelern, [], {
              #klasse: klasse,
              #schueler: schueler,
              #importSource: importSource,
            }),
            returnValue: _i12.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#importKlasseMitSchuelern, [], {
                  #klasse: klasse,
                  #schueler: schueler,
                  #importSource: importSource,
                }),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<_i10.MergeResult> mergeStudentsIntoKlasse({
    required String? klasseId,
    required List<_i5.Student>? neueSchueler,
    required List<_i5.Student>? existierendeSchueler,
    required Map<String, String>? manuellesMatching,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#mergeStudentsIntoKlasse, [], {
              #klasseId: klasseId,
              #neueSchueler: neueSchueler,
              #existierendeSchueler: existierendeSchueler,
              #manuellesMatching: manuellesMatching,
            }),
            returnValue: _i12.Future<_i10.MergeResult>.value(
              _FakeMergeResult_14(
                this,
                Invocation.method(#mergeStudentsIntoKlasse, [], {
                  #klasseId: klasseId,
                  #neueSchueler: neueSchueler,
                  #existierendeSchueler: existierendeSchueler,
                  #manuellesMatching: manuellesMatching,
                }),
              ),
            ),
          )
          as _i12.Future<_i10.MergeResult>);

  @override
  _i12.Future<void> markStudentsAsAusgetreten(
    List<String>? studentIds,
    DateTime? austrittsDatum,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markStudentsAsAusgetreten, [
              studentIds,
              austrittsDatum,
            ]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  double calculateSimpleAverage(List<_i7.Grade>? grades) =>
      (super.noSuchMethod(
            Invocation.method(#calculateSimpleAverage, [grades]),
            returnValue: 0.0,
          )
          as double);

  @override
  double calculateWeightedAverage(
    List<({double gewichtung, _i7.Grade grade})>? gradesWithWeight,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateWeightedAverage, [gradesWithWeight]),
            returnValue: 0.0,
          )
          as double);

  @override
  _i12.Stream<List<_i15.LnExemption>> getLnExemptions() =>
      (super.noSuchMethod(
            Invocation.method(#getLnExemptions, []),
            returnValue: _i12.Stream<List<_i15.LnExemption>>.empty(),
          )
          as _i12.Stream<List<_i15.LnExemption>>);

  @override
  _i12.Future<bool> isStudentExempt(
    String? studentId,
    String? leistungsnachweisId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isStudentExempt, [
              studentId,
              leistungsnachweisId,
            ]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<String> createLnExemption({
    required String? studentId,
    required String? leistungsnachweisId,
    String? grund,
    String? createdBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createLnExemption, [], {
              #studentId: studentId,
              #leistungsnachweisId: leistungsnachweisId,
              #grund: grund,
              #createdBy: createdBy,
            }),
            returnValue: _i12.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#createLnExemption, [], {
                  #studentId: studentId,
                  #leistungsnachweisId: leistungsnachweisId,
                  #grund: grund,
                  #createdBy: createdBy,
                }),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<void> deleteLnExemption(
    String? studentId,
    String? leistungsnachweisId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLnExemption, [
              studentId,
              leistungsnachweisId,
            ]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Stream<List<_i15.LnExemption>> getLnExemptionsByLn(
    String? leistungsnachweisId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLnExemptionsByLn, [leistungsnachweisId]),
            returnValue: _i12.Stream<List<_i15.LnExemption>>.empty(),
          )
          as _i12.Stream<List<_i15.LnExemption>>);

  @override
  _i12.Stream<List<_i11.AppUser>> getAppUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAppUsers, []),
            returnValue: _i12.Stream<List<_i11.AppUser>>.empty(),
          )
          as _i12.Stream<List<_i11.AppUser>>);

  @override
  _i12.Future<_i11.AppUser?> getAppUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAppUser, [id]),
            returnValue: _i12.Future<_i11.AppUser?>.value(),
          )
          as _i12.Future<_i11.AppUser?>);

  @override
  _i12.Future<_i11.AppUser?> getAppUserByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getAppUserByEmail, [email]),
            returnValue: _i12.Future<_i11.AppUser?>.value(),
          )
          as _i12.Future<_i11.AppUser?>);

  @override
  _i12.Future<_i11.AppUser> getAppUserByKuerzel(String? kuerzel) =>
      (super.noSuchMethod(
            Invocation.method(#getAppUserByKuerzel, [kuerzel]),
            returnValue: _i12.Future<_i11.AppUser>.value(
              _FakeAppUser_15(
                this,
                Invocation.method(#getAppUserByKuerzel, [kuerzel]),
              ),
            ),
          )
          as _i12.Future<_i11.AppUser>);

  @override
  _i12.Future<String> createAppUser(_i11.AppUser? user) =>
      (super.noSuchMethod(
            Invocation.method(#createAppUser, [user]),
            returnValue: _i12.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#createAppUser, [user]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<void> createAppUserWithId(String? id, _i11.AppUser? user) =>
      (super.noSuchMethod(
            Invocation.method(#createAppUserWithId, [id, user]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateAppUser(_i11.AppUser? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppUser, [user]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateLastLogin(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastLogin, [userId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deactivateAppUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateAppUser, [userId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> activateAppUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#activateAppUser, [userId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteAppUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAppUser, [userId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateFavoriteKlassen(
    String? userId,
    List<String>? klassenIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateFavoriteKlassen, [userId, klassenIds]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> isKuerzelTaken(String? kuerzel, {String? excludeUserId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #isKuerzelTaken,
              [kuerzel],
              {#excludeUserId: excludeUserId},
            ),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Stream<List<_i16.SchuelerUnterricht>> getSchuelerUnterricht() =>
      (super.noSuchMethod(
            Invocation.method(#getSchuelerUnterricht, []),
            returnValue: _i12.Stream<List<_i16.SchuelerUnterricht>>.empty(),
          )
          as _i12.Stream<List<_i16.SchuelerUnterricht>>);

  @override
  _i12.Stream<List<_i16.SchuelerUnterricht>> getUnterrichtByStudent(
    String? studentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUnterrichtByStudent, [studentId]),
            returnValue: _i12.Stream<List<_i16.SchuelerUnterricht>>.empty(),
          )
          as _i12.Stream<List<_i16.SchuelerUnterricht>>);

  @override
  _i12.Stream<List<_i16.SchuelerUnterricht>> getUnterrichtByLehrer(
    String? lehrerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUnterrichtByLehrer, [lehrerId]),
            returnValue: _i12.Stream<List<_i16.SchuelerUnterricht>>.empty(),
          )
          as _i12.Stream<List<_i16.SchuelerUnterricht>>);

  @override
  _i12.Future<String> createSchuelerUnterricht(
    _i16.SchuelerUnterricht? unterricht,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSchuelerUnterricht, [unterricht]),
            returnValue: _i12.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#createSchuelerUnterricht, [unterricht]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<void> deleteSchuelerUnterricht(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSchuelerUnterricht, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteUnterrichtByStudent(String? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUnterrichtByStudent, [studentId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i8.Klasse>> getKlassenOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getKlassenOnce, []),
            returnValue: _i12.Future<List<_i8.Klasse>>.value(<_i8.Klasse>[]),
          )
          as _i12.Future<List<_i8.Klasse>>);

  @override
  _i12.Future<List<_i6.Subject>> getSubjectsOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectsOnce, []),
            returnValue: _i12.Future<List<_i6.Subject>>.value(<_i6.Subject>[]),
          )
          as _i12.Future<List<_i6.Subject>>);

  @override
  _i12.Future<List<_i11.AppUser>> getAppUsersOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getAppUsersOnce, []),
            returnValue: _i12.Future<List<_i11.AppUser>>.value(
              <_i11.AppUser>[],
            ),
          )
          as _i12.Future<List<_i11.AppUser>>);

  @override
  _i12.Future<List<_i5.Student>> getStudentsOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getStudentsOnce, []),
            returnValue: _i12.Future<List<_i5.Student>>.value(<_i5.Student>[]),
          )
          as _i12.Future<List<_i5.Student>>);

  @override
  _i12.Future<List<_i16.SchuelerUnterricht>> getSchuelerUnterrichtOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getSchuelerUnterrichtOnce, []),
            returnValue: _i12.Future<List<_i16.SchuelerUnterricht>>.value(
              <_i16.SchuelerUnterricht>[],
            ),
          )
          as _i12.Future<List<_i16.SchuelerUnterricht>>);

  @override
  _i12.Future<_i5.Student?> getStudentByAsvId(String? asvId) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentByAsvId, [asvId]),
            returnValue: _i12.Future<_i5.Student?>.value(),
          )
          as _i12.Future<_i5.Student?>);

  @override
  _i12.Future<_i6.Subject?> getSubjectByKuerzel(String? kuerzel) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectByKuerzel, [kuerzel]),
            returnValue: _i12.Future<_i6.Subject?>.value(),
          )
          as _i12.Future<_i6.Subject?>);

  @override
  _i12.Future<_i8.Klasse?> getKlasseByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getKlasseByName, [name]),
            returnValue: _i12.Future<_i8.Klasse?>.value(),
          )
          as _i12.Future<_i8.Klasse?>);
}
