// Mocks generated by Mockito 5.4.6 from annotations
// in induscore/test/widgets/profile/favorites_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:induscore/models/app_user.dart' as _i8;
import 'package:induscore/models/grade.dart' as _i4;
import 'package:induscore/models/klasse.dart' as _i5;
import 'package:induscore/models/leistungsnachweis.dart' as _i6;
import 'package:induscore/models/ln_exemption.dart' as _i11;
import 'package:induscore/models/schueler_unterricht.dart' as _i12;
import 'package:induscore/models/student.dart' as _i2;
import 'package:induscore/models/subject.dart' as _i3;
import 'package:induscore/services/firestore_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStudent_0 extends _i1.SmartFake implements _i2.Student {
  _FakeStudent_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubject_1 extends _i1.SmartFake implements _i3.Subject {
  _FakeSubject_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGrade_2 extends _i1.SmartFake implements _i4.Grade {
  _FakeGrade_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKlasse_3 extends _i1.SmartFake implements _i5.Klasse {
  _FakeKlasse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLeistungsnachweis_4 extends _i1.SmartFake
    implements _i6.Leistungsnachweis {
  _FakeLeistungsnachweis_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMergeResult_5 extends _i1.SmartFake implements _i7.MergeResult {
  _FakeMergeResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppUser_6 extends _i1.SmartFake implements _i8.AppUser {
  _FakeAppUser_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i7.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Stream<List<_i2.Student>> getStudents() =>
      (super.noSuchMethod(
            Invocation.method(#getStudents, []),
            returnValue: _i9.Stream<List<_i2.Student>>.empty(),
          )
          as _i9.Stream<List<_i2.Student>>);

  @override
  _i9.Future<_i2.Student> getStudent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getStudent, [id]),
            returnValue: _i9.Future<_i2.Student>.value(
              _FakeStudent_0(this, Invocation.method(#getStudent, [id])),
            ),
          )
          as _i9.Future<_i2.Student>);

  @override
  _i9.Future<String> createStudent(_i2.Student? student) =>
      (super.noSuchMethod(
            Invocation.method(#createStudent, [student]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createStudent, [student]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> updateStudent(_i2.Student? student) =>
      (super.noSuchMethod(
            Invocation.method(#updateStudent, [student]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteStudent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStudent, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Stream<List<_i2.Student>> getStudentsByKlasse(String? klasseId) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentsByKlasse, [klasseId]),
            returnValue: _i9.Stream<List<_i2.Student>>.empty(),
          )
          as _i9.Stream<List<_i2.Student>>);

  @override
  _i9.Stream<List<_i3.Subject>> getSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getSubjects, []),
            returnValue: _i9.Stream<List<_i3.Subject>>.empty(),
          )
          as _i9.Stream<List<_i3.Subject>>);

  @override
  _i9.Future<_i3.Subject> getSubject(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSubject, [id]),
            returnValue: _i9.Future<_i3.Subject>.value(
              _FakeSubject_1(this, Invocation.method(#getSubject, [id])),
            ),
          )
          as _i9.Future<_i3.Subject>);

  @override
  _i9.Future<String> createSubject(_i3.Subject? subject) =>
      (super.noSuchMethod(
            Invocation.method(#createSubject, [subject]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createSubject, [subject]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> updateSubject(_i3.Subject? subject) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubject, [subject]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteSubject(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubject, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Stream<List<_i4.Grade>> getGrades() =>
      (super.noSuchMethod(
            Invocation.method(#getGrades, []),
            returnValue: _i9.Stream<List<_i4.Grade>>.empty(),
          )
          as _i9.Stream<List<_i4.Grade>>);

  @override
  _i9.Stream<List<_i4.Grade>> getGradesByLeistungsnachweis(
    String? leistungsnachweisId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGradesByLeistungsnachweis, [
              leistungsnachweisId,
            ]),
            returnValue: _i9.Stream<List<_i4.Grade>>.empty(),
          )
          as _i9.Stream<List<_i4.Grade>>);

  @override
  _i9.Stream<List<_i4.Grade>> getGradesByStudent(String? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#getGradesByStudent, [studentId]),
            returnValue: _i9.Stream<List<_i4.Grade>>.empty(),
          )
          as _i9.Stream<List<_i4.Grade>>);

  @override
  _i9.Future<_i4.Grade> getGrade(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGrade, [id]),
            returnValue: _i9.Future<_i4.Grade>.value(
              _FakeGrade_2(this, Invocation.method(#getGrade, [id])),
            ),
          )
          as _i9.Future<_i4.Grade>);

  @override
  _i9.Future<String> createGrade(_i4.Grade? grade) =>
      (super.noSuchMethod(
            Invocation.method(#createGrade, [grade]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createGrade, [grade]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> saveGrades(List<_i4.Grade>? grades) =>
      (super.noSuchMethod(
            Invocation.method(#saveGrades, [grades]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateGrade(_i4.Grade? grade) =>
      (super.noSuchMethod(
            Invocation.method(#updateGrade, [grade]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteGrade(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGrade, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteGradesByLeistungsnachweis(
    String? leistungsnachweisId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGradesByLeistungsnachweis, [
              leistungsnachweisId,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Stream<List<_i5.Klasse>> getKlassen() =>
      (super.noSuchMethod(
            Invocation.method(#getKlassen, []),
            returnValue: _i9.Stream<List<_i5.Klasse>>.empty(),
          )
          as _i9.Stream<List<_i5.Klasse>>);

  @override
  _i9.Future<_i5.Klasse> getKlasse(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getKlasse, [id]),
            returnValue: _i9.Future<_i5.Klasse>.value(
              _FakeKlasse_3(this, Invocation.method(#getKlasse, [id])),
            ),
          )
          as _i9.Future<_i5.Klasse>);

  @override
  _i9.Stream<List<_i5.Klasse>> getKlassenBySchuljahrAndBeruf(
    String? schuljahr,
    String? berufCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getKlassenBySchuljahrAndBeruf, [
              schuljahr,
              berufCode,
            ]),
            returnValue: _i9.Stream<List<_i5.Klasse>>.empty(),
          )
          as _i9.Stream<List<_i5.Klasse>>);

  @override
  _i9.Future<String> createKlasse(_i5.Klasse? klasse) =>
      (super.noSuchMethod(
            Invocation.method(#createKlasse, [klasse]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createKlasse, [klasse]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> updateKlasse(_i5.Klasse? klasse) =>
      (super.noSuchMethod(
            Invocation.method(#updateKlasse, [klasse]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteKlasse(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteKlasse, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Stream<List<_i6.Leistungsnachweis>> getLeistungsnachweise() =>
      (super.noSuchMethod(
            Invocation.method(#getLeistungsnachweise, []),
            returnValue: _i9.Stream<List<_i6.Leistungsnachweis>>.empty(),
          )
          as _i9.Stream<List<_i6.Leistungsnachweis>>);

  @override
  _i9.Future<_i6.Leistungsnachweis> getLeistungsnachweis(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getLeistungsnachweis, [id]),
            returnValue: _i9.Future<_i6.Leistungsnachweis>.value(
              _FakeLeistungsnachweis_4(
                this,
                Invocation.method(#getLeistungsnachweis, [id]),
              ),
            ),
          )
          as _i9.Future<_i6.Leistungsnachweis>);

  @override
  _i9.Stream<List<_i6.Leistungsnachweis>> getLeistungsnachweiseByKlasse(
    String? klasseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLeistungsnachweiseByKlasse, [klasseId]),
            returnValue: _i9.Stream<List<_i6.Leistungsnachweis>>.empty(),
          )
          as _i9.Stream<List<_i6.Leistungsnachweis>>);

  @override
  _i9.Stream<List<_i6.Leistungsnachweis>> getLeistungsnachweiseBySubject(
    String? subjectId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLeistungsnachweiseBySubject, [subjectId]),
            returnValue: _i9.Stream<List<_i6.Leistungsnachweis>>.empty(),
          )
          as _i9.Stream<List<_i6.Leistungsnachweis>>);

  @override
  _i9.Future<String> createLeistungsnachweis(_i6.Leistungsnachweis? ln) =>
      (super.noSuchMethod(
            Invocation.method(#createLeistungsnachweis, [ln]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createLeistungsnachweis, [ln]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> updateLeistungsnachweis(_i6.Leistungsnachweis? ln) =>
      (super.noSuchMethod(
            Invocation.method(#updateLeistungsnachweis, [ln]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteLeistungsnachweis(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLeistungsnachweis, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i5.Klasse?> findExistingKlasse({
    required String? berufCode,
    required int? jahrgangsstufe,
    required int? zeitgruppeNummer,
    required int? laufendeNummer,
    required String? schuljahr,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findExistingKlasse, [], {
              #berufCode: berufCode,
              #jahrgangsstufe: jahrgangsstufe,
              #zeitgruppeNummer: zeitgruppeNummer,
              #laufendeNummer: laufendeNummer,
              #schuljahr: schuljahr,
            }),
            returnValue: _i9.Future<_i5.Klasse?>.value(),
          )
          as _i9.Future<_i5.Klasse?>);

  @override
  _i9.Future<List<_i2.Student>> getStudentsByKlasseOnce(String? klasseId) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentsByKlasseOnce, [klasseId]),
            returnValue: _i9.Future<List<_i2.Student>>.value(<_i2.Student>[]),
          )
          as _i9.Future<List<_i2.Student>>);

  @override
  _i9.Future<String> importKlasseMitSchuelern({
    required _i5.Klasse? klasse,
    required List<_i2.Student>? schueler,
    String? importSource = 'pdf',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#importKlasseMitSchuelern, [], {
              #klasse: klasse,
              #schueler: schueler,
              #importSource: importSource,
            }),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#importKlasseMitSchuelern, [], {
                  #klasse: klasse,
                  #schueler: schueler,
                  #importSource: importSource,
                }),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<_i7.MergeResult> mergeStudentsIntoKlasse({
    required String? klasseId,
    required List<_i2.Student>? neueSchueler,
    required List<_i2.Student>? existierendeSchueler,
    required Map<String, String>? manuellesMatching,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#mergeStudentsIntoKlasse, [], {
              #klasseId: klasseId,
              #neueSchueler: neueSchueler,
              #existierendeSchueler: existierendeSchueler,
              #manuellesMatching: manuellesMatching,
            }),
            returnValue: _i9.Future<_i7.MergeResult>.value(
              _FakeMergeResult_5(
                this,
                Invocation.method(#mergeStudentsIntoKlasse, [], {
                  #klasseId: klasseId,
                  #neueSchueler: neueSchueler,
                  #existierendeSchueler: existierendeSchueler,
                  #manuellesMatching: manuellesMatching,
                }),
              ),
            ),
          )
          as _i9.Future<_i7.MergeResult>);

  @override
  _i9.Future<void> markStudentsAsAusgetreten(
    List<String>? studentIds,
    DateTime? austrittsDatum,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markStudentsAsAusgetreten, [
              studentIds,
              austrittsDatum,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  double calculateSimpleAverage(List<_i4.Grade>? grades) =>
      (super.noSuchMethod(
            Invocation.method(#calculateSimpleAverage, [grades]),
            returnValue: 0.0,
          )
          as double);

  @override
  double calculateWeightedAverage(
    List<({double gewichtung, _i4.Grade grade})>? gradesWithWeight,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateWeightedAverage, [gradesWithWeight]),
            returnValue: 0.0,
          )
          as double);

  @override
  _i9.Stream<List<_i11.LnExemption>> getLnExemptions() =>
      (super.noSuchMethod(
            Invocation.method(#getLnExemptions, []),
            returnValue: _i9.Stream<List<_i11.LnExemption>>.empty(),
          )
          as _i9.Stream<List<_i11.LnExemption>>);

  @override
  _i9.Future<bool> isStudentExempt(
    String? studentId,
    String? leistungsnachweisId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isStudentExempt, [
              studentId,
              leistungsnachweisId,
            ]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<String> createLnExemption({
    required String? studentId,
    required String? leistungsnachweisId,
    String? grund,
    String? createdBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createLnExemption, [], {
              #studentId: studentId,
              #leistungsnachweisId: leistungsnachweisId,
              #grund: grund,
              #createdBy: createdBy,
            }),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createLnExemption, [], {
                  #studentId: studentId,
                  #leistungsnachweisId: leistungsnachweisId,
                  #grund: grund,
                  #createdBy: createdBy,
                }),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> deleteLnExemption(
    String? studentId,
    String? leistungsnachweisId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLnExemption, [
              studentId,
              leistungsnachweisId,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Stream<List<_i11.LnExemption>> getLnExemptionsByLn(
    String? leistungsnachweisId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLnExemptionsByLn, [leistungsnachweisId]),
            returnValue: _i9.Stream<List<_i11.LnExemption>>.empty(),
          )
          as _i9.Stream<List<_i11.LnExemption>>);

  @override
  _i9.Stream<List<_i8.AppUser>> getAppUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAppUsers, []),
            returnValue: _i9.Stream<List<_i8.AppUser>>.empty(),
          )
          as _i9.Stream<List<_i8.AppUser>>);

  @override
  _i9.Future<_i8.AppUser?> getAppUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAppUser, [id]),
            returnValue: _i9.Future<_i8.AppUser?>.value(),
          )
          as _i9.Future<_i8.AppUser?>);

  @override
  _i9.Future<_i8.AppUser?> getAppUserByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getAppUserByEmail, [email]),
            returnValue: _i9.Future<_i8.AppUser?>.value(),
          )
          as _i9.Future<_i8.AppUser?>);

  @override
  _i9.Future<_i8.AppUser> getAppUserByKuerzel(String? kuerzel) =>
      (super.noSuchMethod(
            Invocation.method(#getAppUserByKuerzel, [kuerzel]),
            returnValue: _i9.Future<_i8.AppUser>.value(
              _FakeAppUser_6(
                this,
                Invocation.method(#getAppUserByKuerzel, [kuerzel]),
              ),
            ),
          )
          as _i9.Future<_i8.AppUser>);

  @override
  _i9.Future<String> createAppUser(_i8.AppUser? user) =>
      (super.noSuchMethod(
            Invocation.method(#createAppUser, [user]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createAppUser, [user]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> createAppUserWithId(String? id, _i8.AppUser? user) =>
      (super.noSuchMethod(
            Invocation.method(#createAppUserWithId, [id, user]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateAppUser(_i8.AppUser? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppUser, [user]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateLastLogin(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastLogin, [userId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deactivateAppUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateAppUser, [userId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> activateAppUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#activateAppUser, [userId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteAppUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAppUser, [userId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateFavoriteKlassen(
    String? userId,
    List<String>? klassenIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateFavoriteKlassen, [userId, klassenIds]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool> isKuerzelTaken(String? kuerzel, {String? excludeUserId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #isKuerzelTaken,
              [kuerzel],
              {#excludeUserId: excludeUserId},
            ),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Stream<List<_i12.SchuelerUnterricht>> getSchuelerUnterricht() =>
      (super.noSuchMethod(
            Invocation.method(#getSchuelerUnterricht, []),
            returnValue: _i9.Stream<List<_i12.SchuelerUnterricht>>.empty(),
          )
          as _i9.Stream<List<_i12.SchuelerUnterricht>>);

  @override
  _i9.Stream<List<_i12.SchuelerUnterricht>> getUnterrichtByStudent(
    String? studentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUnterrichtByStudent, [studentId]),
            returnValue: _i9.Stream<List<_i12.SchuelerUnterricht>>.empty(),
          )
          as _i9.Stream<List<_i12.SchuelerUnterricht>>);

  @override
  _i9.Stream<List<_i12.SchuelerUnterricht>> getUnterrichtByLehrer(
    String? lehrerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUnterrichtByLehrer, [lehrerId]),
            returnValue: _i9.Stream<List<_i12.SchuelerUnterricht>>.empty(),
          )
          as _i9.Stream<List<_i12.SchuelerUnterricht>>);

  @override
  _i9.Future<String> createSchuelerUnterricht(
    _i12.SchuelerUnterricht? unterricht,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSchuelerUnterricht, [unterricht]),
            returnValue: _i9.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createSchuelerUnterricht, [unterricht]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> deleteSchuelerUnterricht(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSchuelerUnterricht, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteUnterrichtByStudent(String? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUnterrichtByStudent, [studentId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i5.Klasse>> getKlassenOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getKlassenOnce, []),
            returnValue: _i9.Future<List<_i5.Klasse>>.value(<_i5.Klasse>[]),
          )
          as _i9.Future<List<_i5.Klasse>>);

  @override
  _i9.Future<List<_i3.Subject>> getSubjectsOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectsOnce, []),
            returnValue: _i9.Future<List<_i3.Subject>>.value(<_i3.Subject>[]),
          )
          as _i9.Future<List<_i3.Subject>>);

  @override
  _i9.Future<List<_i8.AppUser>> getAppUsersOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getAppUsersOnce, []),
            returnValue: _i9.Future<List<_i8.AppUser>>.value(<_i8.AppUser>[]),
          )
          as _i9.Future<List<_i8.AppUser>>);

  @override
  _i9.Future<List<_i2.Student>> getStudentsOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getStudentsOnce, []),
            returnValue: _i9.Future<List<_i2.Student>>.value(<_i2.Student>[]),
          )
          as _i9.Future<List<_i2.Student>>);

  @override
  _i9.Future<List<_i12.SchuelerUnterricht>> getSchuelerUnterrichtOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getSchuelerUnterrichtOnce, []),
            returnValue: _i9.Future<List<_i12.SchuelerUnterricht>>.value(
              <_i12.SchuelerUnterricht>[],
            ),
          )
          as _i9.Future<List<_i12.SchuelerUnterricht>>);

  @override
  _i9.Future<_i2.Student?> getStudentByAsvId(String? asvId) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentByAsvId, [asvId]),
            returnValue: _i9.Future<_i2.Student?>.value(),
          )
          as _i9.Future<_i2.Student?>);

  @override
  _i9.Future<_i3.Subject?> getSubjectByKuerzel(String? kuerzel) =>
      (super.noSuchMethod(
            Invocation.method(#getSubjectByKuerzel, [kuerzel]),
            returnValue: _i9.Future<_i3.Subject?>.value(),
          )
          as _i9.Future<_i3.Subject?>);

  @override
  _i9.Future<_i5.Klasse?> getKlasseByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getKlasseByName, [name]),
            returnValue: _i9.Future<_i5.Klasse?>.value(),
          )
          as _i9.Future<_i5.Klasse?>);
}
